# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: https://jumpgh.github.io/proxia-site/
title: proxia
email: sales@proxia.ru
tel: +7(495)204-60-10
description: >- # this means to ignore newlines until "baseurl:"
  ООО "ПРОКСИА" 140180 г. Жуковский, Московской области, ул. Лесная д.5, офис 101
  +7 (495) 204-60-10  доб: 413, 459;
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# navbar
nav:
  - title: продукты
    url: {{site.baseurl}}/products/
  - title: партнерам
    url: {{site.baseurl}}/partners/
  - title: платформа IoT
    url: {{site.baseurl}}/platform/
  - title: use case
    url: {{site.baseurl}}/usecase/
    submenu:
      - title: case 1
        url: {{site.baseurl}}/usecase/case1.html
      - title: case 2
        url: {{site.baseurl}}/usecase/case2.html
  - title: about
    url: {{site.baseurl}}/about/


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  products:
    output: true
  usecase:
    output: true
  news:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
